### PR TITLE
Add ipow

### PR DESCRIPTION
**Pull request by loikki**
Hi,

I am using the function ipow (e.g. a **= 5) and it seems that you forgot to implement it.
Here is my implementation.

Thank you very much for this amazing work!

Best,

### CODE REVIEW

**Comment by inducer** [comment]
Thanks! This looks good. Could you add a test? (Sorry to make you do extra work.)

**Comment by loikki** [comment]
Ok, I will do it

**Comment by loikki** [comment]
Done

I put the test inside the normal pow function

**Comment by inducer** [comment]
Thanks for your contribution!

**Pull request merged**
