### PR TITLE
Add way to access primary context

### PR DESCRIPTION
**Pull request by apark263**
Not sure if this would be the best way to do things, but I need a way to access and then make the primary context current for a separate shared lib that uses the runtime api.

### CODE REVIEW

**Comment by inducer** [comment]
One difficulty is that this doesn't really interact with the CUDA 2.0-vintage "context stack" functionality that's still littered throughout PyCUDA. IIRC, CUDA 5-ish deprecated the context stack in favor of setter/getter functions, so I expect that refactor would have to be done before this.

**Comment by inducer** [comment]
Nonetheless, thank you for your contribution! I'll leave this open until we can come up with a solution that addresses interaction with/gets rid of the context stack.

**Comment by peter64** [comment]
Hey guys, I'm trying to use pycuda in conjunction with numba but I keep running into issues because numba wants to use the primary context, but I can't seem to find a way to have pycuda use the primary context. This results in numba throwing an error "Numba cannot operate on non-primary CUDA context".
I was curious to know if there was any work-around for this, it seems like the functionality proposed in this pull request might resolve the issue, however I'm not familiar enough with cuda to be sure.

**Comment by peter64** [comment]
Just wanted to update here, that this did solve my issue *almost* it required one modification which I'm pretty sure isn't correct without some corresponding clean-up code to remove the retained context from the context_stack.

  boost::shared_ptr<context> device::retain_primary_context()
  {
    CUcontext ctx;
    CUDAPP_CALL_GUARDED(cuDevicePrimaryCtxRetain, (&ctx, m_device));
    boost::shared_ptr<context> result(new context(ctx));
    context_stack::get().push(result);
    CUDAPP_CALL_GUARDED(cuCtxSetCurrent, (ctx));
    return result;
  }

I also posted this question on nvidias dev site just incase anyone else is trying to do the same thing and might find this pull request useful.

https://devtalk.nvidia.com/default/topic/1066013/cuda-programming-and-performance/question-regarding-opengl-cuda-interop-with-numba-and-pycuda-primary-context-issue-/?offset=3#5398351

**Comment by inducer** [comment]
This eventually got done here: https://gitlab.tiker.net/inducer/pycuda/-/merge_requests/21

Thanks again for proposing this.

**Pull request closed without merging**
