### PR TITLE
Added function to create CUDA Arrays directly from GPUArrays

### PR DESCRIPTION
**Pull request by zamorays**
Just to complete functionality, i'm adding a function to create CUDA arrays from GPUArrays. Testing it with a previous fp_surface test, modifying the source of the CUDA Array to device. In the future support of Textures and Surface Objects maybe performance interesting ....

### CODE REVIEW

**Comment by inducer** [comment]
Thanks for your contribution! Two comments:

* PEP8 (i.e. mainly that the indentation should be 4 spaces deep at each level)
* Can you add these functions to the docs?

**Comment by zamorays** [comment]
All right, i'm working on that.

**Comment by zamorays** [comment]
I think is already:
*  I changed a little the driver tests to use new functions.
*  Correct *driver.py* to accomplish PEP8.
*  New functions added to documentation and correctly builded.

**Comment by inducer** [comment]
Looks great. Thanks for your contribution!

**Pull request merged**
